version: '3.8'

services:
  flask-app-service:
    build: ./backend/app
    volumes:
      - ./backend/app:/app
    ports:
      - "44665:5000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      app-network:
        ipv4_address: 172.28.32.10  # IP fixo para o container backend

  frontend:
    build:
      context: ./frontend/
    ports:
      - "4200:4200"
    depends_on:
      - flask-app-service
    networks:
      - app-network
    command: ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.32.0/24"  # Definindo a faixa de IPs
          gateway: "172.28.32.1"    # Definindo o gateway para a rede
